### ISSUE TITLE
Can't generate build dependencies

### ISSUE THREAD

**Issue by JeremieBourque1** [patrick--/SLAM-Exploration#1]
When in the directory `SLAM-Exploration\buid` and execute the command `cmake ..` the following error is returned: `CMake Error: The source directory "/home/jeremie/SLAM-Exploration" does not appear to contain CMakeLists.txt.`

**Comment by ptrks** [comment]
@JeremieBourque1 Good catch! It looks like I may have omitted the main CMake file. I'll get that fixed and merged asap.

**Comment by ptrks** [comment]
@JeremieBourque1 Please pull again and let me know if you run into the same problem
